######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 9 23:17:33 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += EinClient.h MainWindow.h
SOURCES += EinClient.cpp MainWindow.cpp TestMainWindow.cpp
