######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 11 22:43:22 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += EinClient.h MainWindow.h SendMesg.h SendMesg.cpp ../Include/Network.h
SOURCES += EinClient.cpp MainWindow.cpp SendMesg.cpp TestMainWindow.cpp
